name: dart_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shared:
    path: "../shared"
  uuid: ^4.5.1
  tuple: ^2.0.0
  collection: ^1.19.1
  logger: ^2.4.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.0.4
  mockito: ^5.0.8
